#version: '3'
#services:
#  myapp:
#    image: booking
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#  db:
#    image: postgres:12-alpine
#    environment:
#      - POSTGRES_DB=Booking
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=shinopy
version: '3'
services:
  myapp:
    image: booking
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=Booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shinopy
  web:
    image: bookingfrontend
    ports:
      - "4200:80"
    depends_on:
      - myapp





